
-- Exercise 1.1
SELECT * FROM INSTRUMENTS WHERE id = 5;


-- Exercise 1.2
SELECT INSTRUMENTS.name, INSTRUMENTS.price FROM INSTRUMENTS INNER JOIN BANDS ON BANDS.id = INSTRUMENTS.id WHERE BANDS.name LIKE "%Metallica%";

-- Exercise 1.3
SELECT BANDS.name, COUNT(INSTRUMENTS_IN_BAND.instrument_id) FROM ((INSTRUMENTS_IN_BAND INNER JOIN INSTRUMENTS ON INSTRUMENTS.id = INSTRUMENTS_IN_BAND.instrument_id) INNER JOIN BAND ON INSTRUMENTS_IN_BAND.band_id = BAND.id GROUP BY BANDS.name;